name: CI

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [13]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Install required packages
        run: yarn install
      - name: Build React app
        run: yarn build
      - name: Deploy firebase hosting
        run: >-
          firebase use $PROJECT_NAME &&
          firebase deploy
        env:
          PROJECT_NAME: food-random-265418
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
